### ISSUE TITLE
sway wm shortcuts problems

### ISSUE THREAD

**Issue by sah4ez** [yamadharma/yamadharma.github.io#1]
Доброго времени суток! 

Подскажите, как решили проблему использования шоткатов при переключенном active layout.

Допустим с включенным layout ru - не работают комбинации mod+j

**Comment by yamadharma** [comment]
Пробовали ли Вы `bindsym --to-code` ?

**Comment by sah4ez** [comment]
Да, пробовал по разному. и через явно определение кода. не заработало. Плюс возникла проблема с интеграцией через x2x - пришлось откатиться.
